Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pudb/__init__.py", line 83, in runscript
    dbg._runscript(mainpyfile)
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 419, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "1003.py", line 3, in <module>
    n = int(input())
  File "1003.py", line 3, in <module>
    n = int(input())
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 173, in dispatch_line
    self.user_line(frame)
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 371, in user_line
    self.interaction(frame)
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 339, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 2079, in call_with_ui
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 2307, in interaction
    self.event_loop()
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 2273, in event_loop
    toplevel.keypress(self.size, k)
  File "/usr/local/lib/python3.6/site-packages/pudb/ui_tools.py", line 96, in keypress
    result = self._w.keypress(size, key)
  File "/usr/local/lib/python3.6/site-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python3.6/site-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib/python3.6/site-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python3.6/site-packages/pudb/ui_tools.py", line 101, in keypress
    return handler(self, size, key)
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 1094, in step
    end()
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 1079, in end
    self.debugger.save_breakpoints()
  File "/usr/local/lib/python3.6/site-packages/pudb/debugger.py", line 235, in save_breakpoints
    for fn, bp_lst in self.get_all_breaks().items()
  File "/usr/local/lib/python3.6/site-packages/pudb/settings.py", line 493, in save_breakpoints
    histfile = open(get_breakpoints_file_name(), 'w')
PermissionError: [Errno 13] Permission denied: '/Users/seul/.config/pudb/saved-breakpoints-3.6'
